site_name: KP Dagger Documentation
site_description: Network device configuration security analysis tool
site_url: https://flyguy62n.github.io/kp-dagger
repo_url: https://github.com/flyguy62n/kp-dagger
repo_name: flyguy62n/kp-dagger

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/index.md
    - First Analysis: getting-started/first-analysis.md
  - Architecture:
    - Overview: architecture/overview.md
    - Data Models: architecture/data-models.md
    - Dependency Injection: architecture/dependency-injection.md
    - Project Structure: architecture/PROJECT_STRUCTURE.md
  - Security:
    - Encryption Design: security/encryption-design.md
    - Implementation Summary: security/implementation-summary.md
  - Development:
    - Contributing: development/contributing.md
    - GitHub Issues: development/GITHUB_ISSUES.md
    - Roadmap: development/ROADMAP.md
    - Dependency Injection Implementation: implementation/DEPENDENCY_INJECTION_IMPLEMENTATION.md

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flyguy62n/kp-dagger
  version:
    provider: mike

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js